TM Sprint-12 code as delivered. Failed to build with 11 warnings & 5 errors as below.
Warning	1	warning C4100: 'sender' : unreferenced formal parameter	c:\Projects\TM-Sprint-12\Scor\crx\crx\CrxPrinter.cpp	45	crx
Warning	2	warning C4100: 'logMessage' : unreferenced formal parameter	c:\Projects\TM-Sprint-12\Scor\crx\crx\crx_message_stub.cpp	69	crx
Warning	3	warning C4100: 'userMessage' : unreferenced formal parameter	c:\Projects\TM-Sprint-12\Scor\crx\crx\crx_message_stub.cpp	69	crx
Warning	4	warning C4100: 'title' : unreferenced formal parameter	c:\Projects\TM-Sprint-12\Scor\crx\crx\crx_message_stub.cpp	68	crx
Warning	5	warning C4100: 'severity' : unreferenced formal parameter	c:\Projects\TM-Sprint-12\Scor\crx\crx\crx_message_stub.cpp	68	crx
Warning	6	Reference to type 'AtCor.Scor.CrossCutting.DatabaseManager.CrxStructPWAMeasurementData' claims it is defined in 'c:\Projects\TM-Sprint-12\Scor\Debug\crx.dll', but it could not be found	c:\Projects\TM-Sprint-12\Scor\Debug\biz.dll	gui
Warning	7	warning C4965: implicit box of integer 0; use nullptr or explicit cast	c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp	576	TestDal
Warning	8	warning C4965: implicit box of integer 0; use nullptr or explicit cast	c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp	731	TestDal
Warning	9	warning C4965: implicit box of integer 0; use nullptr or explicit cast	c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp	732	TestDal
Warning	10	warning C4965: implicit box of integer 0; use nullptr or explicit cast	c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp	733	TestDal
Warning	11	warning C4965: implicit box of integer 0; use nullptr or explicit cast	c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp	735	TestDal
Error	12	error C2039: '_sentPacketSequenceNumber' : is not a member of 'AtCor::Scor::DataAccess::DalCommandInterface_Accessor'	c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp	768	TestDal
Error	13	error C2039: 'SentPacketSequenceNumber' : is not a member of 'AtCor::Scor::DataAccess::DalCommandInterface_Accessor'	c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp	831	TestDal
Error	14	error C2065: 'SentPacketSequenceNumber' : undeclared identifier	c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp	831	TestDal
Error	15	error C2039: 'SentPacketSequenceNumber' : is not a member of 'AtCor::Scor::DataAccess::DalCommandInterface_Accessor'	c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp	849	TestDal
Error	16	error C2065: 'SentPacketSequenceNumber' : undeclared identifier	c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp	849	TestDal


git-svn-id: https://sfs.atcorau.local/svn/SoftwareRepository/trunk/PN022@335 a8a9b14d-6b92-5b4b-9153-4cd90bb22c97