TM Sprint-12 rebuild and dry run ok after removing DalCommandInterfaceTest.cpp from TestDal to resolve build errors as advised by TM. (See below)
From: Dsouza, Deepak [mailto:Deepak.Dsouza@lionbridge.com] 
Sent: Tuesday, 12 July 2011 3:21 PM
To: Victor Aung
Cc: Mahadik, Pritam; Yoon Lee; Mishra, Smarajit
Subject: RE: Sprint 12 Delivery

Hi Victor,

Please see our explanations below in red [i.e. TM:].

Regards,
Deepak

From: Victor Aung [mailto:v.aung@atcormedical.com] 
Sent: Monday, July 11, 2011 12:47 PM
To: Dsouza, Deepak; Mishra, Smarajit
Cc: Mahadik, Pritam; Yoon Lee
Subject: FW: Sprint 12 Delivery

Hi Deepak, Smarajit,

I’m catching up to rebuild TM delivered Sprint-12 solution and got some warnings and errors as below.

Did I miss anything to update and resolve these warnings and errors in CRX and DAL?

Thanks,
Victor

TM: Warning 1: This warning will be removed. 
Warning       1      warning C4100: 'sender' : unreferenced formal parameter       c:\Projects\TM-Sprint-12\Scor\crx\crx\CrxPrinter.cpp    45     crx
TM: Warnings 2-5: These four warnings below are generating in stub files, so we have not changed them. Once these files are removed, these warnings will go away.
Warning       2      warning C4100: 'logMessage' : unreferenced formal parameter   c:\Projects\TM-Sprint-12\Scor\crx\crx\crx_message_stub.cpp     69     crx
Warning       3      warning C4100: 'userMessage' : unreferenced formal parameter  c:\Projects\TM-Sprint-12\Scor\crx\crx\crx_message_stub.cpp     69     crx
Warning       4      warning C4100: 'title' : unreferenced formal parameter c:\Projects\TM-Sprint-12\Scor\crx\crx\crx_message_stub.cpp     68     crx
Warning       5      warning C4100: 'severity' : unreferenced formal parameter     c:\Projects\TM-Sprint-12\Scor\crx\crx\crx_message_stub.cpp     68     crx
TM: Warnings 7-11: We have tried my best to remove the warning, including using explicit cast, but the warning still appears. So I have left them as they are. All other warnings in DAL and TestDal were eliminated
Warning       7      warning C4965: implicit box of integer 0; use nullptr or explicit cast       c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp       576    TestDal
Warning       8      warning C4965: implicit box of integer 0; use nullptr or explicit cast       c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp       731    TestDal
Warning       9      warning C4965: implicit box of integer 0; use nullptr or explicit cast       c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp       732    TestDal
Warning       10     warning C4965: implicit box of integer 0; use nullptr or explicit cast       c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp       733    TestDal
Warning       11     warning C4965: implicit box of integer 0; use nullptr or explicit cast       c:\Projects\TM-Sprint-12\Scor\TestDal\DalStatusHandlerTest.cpp       735    TestDal
TM: Warnings 12-16: I didn’t send the updated DalCommandInterfaceTest.cpp test file since I was working on further changes on the classes. Please remove this file from the solution and compile the test cases. 
Error  12     error C2039: '_sentPacketSequenceNumber' : is not a member of 'AtCor::Scor::DataAccess::DalCommandInterface_Accessor'       c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp     768    TestDal
Error  13     error C2039: 'SentPacketSequenceNumber' : is not a member of 'AtCor::Scor::DataAccess::DalCommandInterface_Accessor'       c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp     831    TestDal
Error  14     error C2065: 'SentPacketSequenceNumber' : undeclared identifier      c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp     831    TestDal
Error  15     error C2039: 'SentPacketSequenceNumber' : is not a member of 'AtCor::Scor::DataAccess::DalCommandInterface_Accessor'       c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp     849    TestDal
Error  16     error C2065: 'SentPacketSequenceNumber' : undeclared identifier      c:\Projects\TM-Sprint-12\Scor\TestDal\DalCommandInterfaceTest.cpp     849    TestDal



git-svn-id: https://sfs.atcorau.local/svn/SoftwareRepository/trunk/PN022@338 a8a9b14d-6b92-5b4b-9153-4cd90bb22c97